# Generated by Django 4.0.10 on 2023-08-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField(blank=True, default='2000-12-31', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=50)),
                ('price', models.FloatField(default=9.99)),
                ('quantity', models.FloatField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='item_images/dflt.png', upload_to='item_images')),
            ],
        ),
    ]
